version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
  redis:
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
