version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - nestjs-template-postgres:/data/db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  nestjs-template-postgres:
