version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - nestjs-template-postgres:/data/db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  nestjs-template-postgres:
